services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://lowmill.nomorepartiessite.ru/api/afisha
        - VITE_CDN_URL=https://lowmill.nomorepartiessite.ru/content/afisha
    image: ghcr.io/lishainik/film-react-nest-frontend:latest
    restart: unless-stopped
    volumes:
      - frontend_dist:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/lishainik/film-react-nest-backend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ghcr.io/lishainik/film-react-nest-nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - '8080:80'
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  frontend_dist:
  postgres_data:
  pgadmin_data: